# Generated by Django 5.1.6 on 2025-02-27 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_transactions', to='trade.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_transactions', to='trade.order'),
        ),
    ]
